# Generated by Django 4.2.3 on 2023-07-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Name')),
                ('user_surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('number_phone', models.CharField(max_length=20)),
                ('citty', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('product_id', models.IntegerField(verbose_name='Product ID')),
                ('quantity', models.IntegerField(verbose_name='Product quantity')),
                ('photo', models.ImageField(upload_to='products/', verbose_name='Photo of product')),
            ],
        ),
    ]
