# Generated by Django 4.2.3 on 2023-07-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='numberphone',
            field=models.CharField(default=None, max_length=20, verbose_name='Number Phone'),
        ),
    ]
