# Generated by Django 4.2.3 on 2023-07-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_buyer_numberphone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
